rack/rack-contrib

- lib/rack/contrib/locale.rb
This will prevent us to overwrite the Content-Language header if
the application sets it properly.
Fixes #88
> Preventing unintended overwrite of Content-Language header

- README.md
This includes:
* marking things with backticks to indicate that they are code or code-adjacent
* adding additional spaces so code blocks display properly
* sorting component list in alphabetical order
The intent is to make it easier to read on GitHub
> Formatting-only changes to README.md

- Rakefile
- rack-contrib.gemspec
> Remove deprecated 'rake/rdoctask', replace with new invocation.

- lib/rack/contrib/static_cache.rb
- test/spec_rack_static_cache.rb
Server side caching techniques shouldn't be disallowed.
See: https://github.com/rack/rack-contrib/commit/3f42d3afe7323d322567d77cd404fb5bd8d9f1eb#commitcomment-5084830
> Allow Etag/Last-Modified headers in Rack::StaticCache

- lib/rack/contrib.rb
- rack-contrib.gemspec
It's used for managing the release versions, but should not be included in the dependencies for others that depend on rack-contrib.
Lookup version number from our own gem spec instead.
> Released version should not depend on git-version-bump

- lib/rack/contrib/not_found.rb
- test/404.html
- test/spec_rack_not_found.rb
The `path` argument to `NotFound` is now optional, and if not provided a default response is returned instead of the file contents.
The tests have also been updated to check Content-Length is correct.
Fixes #117.
> Add a default response to Rack::NotFound if no 404 page specified

- lib/rack/contrib/locale.rb
- test/gemfiles/minimum_versions
- test/spec_rack_locale.rb
This PR implements https://github.com/rack/rack-contrib/issues/14
When the enforce_available_locales flag is enabled, which is the default setting a locale that is not in the list of available locales an InvalidLocale exception is raised. With this changes we're going to set only available locales when is enabled, and any locale when it's not.
A slightly difference with the proposal code from the issue is that we're comparing the full language codes without fallback. So I'm not sure if this PR is too restricted in this way
> When enforce_available_locales is enabled only set available locales

- lib/rack/contrib/post_body_content_type_parser.rb
- test/spec_rack_post_body_content_type_parser.rb
PostBodyContentTypeParser will stop at 500 error if body and content-type are inconsistent.
e.g. POST as `content-type=application/json` but passed body `foobar`.
With this pull request, set the response to 400 and tell the client that the cause of the error is in the request.
> return 400 bad request when contradiction between body and type

- lib/rack/contrib/jsonp.rb
The current regex for valid callbacks suffers from [catastrophic backtracking](https://www.regular-expressions.info/catastrophic.html). It is all good if the input string is a valid one. But, if an invalid character is included, it becomes very slow to compute.
These are some tests with invalid inputs comprised of valid characters and an invalid one at the last character. This is all in function of the length of the ok characters' string:
```ruby
require 'benchmark/ips'
ALLOWED_CHARS =  ('A'..'Z').to_a + ('a'..'z').to_a + ('0'..'9').to_a + %w(. _)
VALID_JS_VAR    = /[a-zA-Z_$][\w$]*/
VALID_CALLBACK  = /\A#{VALID_JS_VAR}(?:\.?#{VALID_JS_VAR})*\z/
Benchmark.ips do |x|
(1..30).each do |i|
string = ALLOWED_CHARS.take(i).join + '"'
x.report("old #{i}") { string =~ VALID_CALLBACK }
x.compare! …
```
> Replace regex without catastrophic backtracking

- lib/rack/contrib/locale.rb
- test/spec_rack_locale.rb
Address #135 . Currently an Undefined method raises if none of Accept-Language matches to I18n.available_locales.
> Rack::Locale use default_locale if none matches

- lib/rack/contrib/nested_params.rb
Currently 'foo=1&foo=2' is parsed to {'foo' => '1'}, in 2.0 it will be parsed to {'foo' => '2'}
---
Based off Rack 2.0 conversation in #137
> Add Rack 2.0 deprecation warning to NestedParams

- lib/rack/contrib/mailexceptions.rb
- lib/rack/contrib/response_cache.rb
- lib/rack/contrib/static_cache.rb
- test/spec_rack_response_cache.rb
This PR updates a few mis-spellings.
```
$ find . | misspellings -f -
./lib/rack/contrib/mailexceptions.rb:93: compability -> "compatibility"
./lib/rack/contrib/response_cache.rb:26: Reponse -> "Response"
./lib/rack/contrib/response_cache.rb:45: reponse -> "response"
./lib/rack/contrib/static_cache.rb:19: unneccessary -> "unnecessary"
./lib/rack/contrib/static_cache.rb:43: begining -> "beginning"
./test/spec_rack_response_cache.rb:59: sucessful -> "successful"
```
> Misspellings: fixed

- .travis.yml
This bumps the versions of ruby that travis uses to test.
FWIW I attempted testing against ruby-head as well (since 2.5 should be out soon) but something farther up the stack throws errors.  I'll try to figure that out and PR something separately.
> update rubies in travis configs

- lib/rack/contrib/not_found.rb
- test/spec_rack_not_found.rb
This resolves #143 
As noted in the issue, Rack::NotFound is not returning the correct content-length when multibyte characters are involved.  This fixes it as suggested by @znz 
Failing test is included.
> Correct Content-Length bug of Rack::NotFound

- rack-contrib.gemspec
> [ci skip] Update rack-contrib.gemspec

- rack-contrib.gemspec
Right now, every single time we install the gem, we got a warning:
```
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed on or after 2018-12-01.
```
this PR just remove the `has_rdoc` assignment to kill the warn message
> Removing has_rdoc deprecation warning

- .travis.yml
This PR updates the Ruby versions in the CI matrix.
It also removes an unused Travis setting (sudo: false).
> Travis: update MRI versions

- lib/rack/contrib/csshttprequest.rb
- lib/rack/contrib/jsonp.rb
- lib/rack/contrib/post_body_content_type_parser.rb
I'm working on a performance improvement to PostBodyContentTypeParser, and figured I should close #148 before I submit any further changes.
> Use bytesize instead of size for Content-Length (fixes #148)

- lib/rack/contrib/response_cache.rb
- test/spec_rack_response_cache.rb
Fixes #155, and makes the inline documentation a bit more explicit.
> Make Rack::ResponseCache headers case-insensitive

- test/spec_rack_access.rb
- test/spec_rack_backstage.rb
- test/spec_rack_bounce_favicon.rb
- test/spec_rack_callbacks.rb
- test/spec_rack_common_cookies.rb
- test/spec_rack_config.rb
- test/spec_rack_contrib.rb
- test/spec_rack_cookies.rb
- test/spec_rack_csshttprequest.rb
- test/spec_rack_deflect.rb
- test/spec_rack_enforce_valid_encoding.rb
- test/spec_rack_evil.rb
- test/spec_rack_expectation_cascade.rb
- test/spec_rack_host_meta.rb
- test/spec_rack_jsonp.rb
- test/spec_rack_lighttpd_script_name_fix.rb
- test/spec_rack_locale.rb
- test/spec_rack_mailexceptions.rb
- test/spec_rack_nested_params.rb
- test/spec_rack_not_found.rb
- test/spec_rack_post_body_content_type_parser.rb
- test/spec_rack_proctitle.rb
- test/spec_rack_profiler.rb
- test/spec_rack_relative_redirect.rb
- test/spec_rack_response_cache.rb
- test/spec_rack_response_headers.rb
- test/spec_rack_runtime.rb
- test/spec_rack_simple_endpoint.rb
- test/spec_rack_static_cache.rb
- test/spec_rack_try_static.rb
Changes:
- fixed failing specs
- fixed MiniTest deprecation warnings
There were failings specs in `test/spec_rack_simple_endpoint.rb` file like this one:
```
Rack::SimpleEndpoint#test_0002_calls downstream app when path matches but method does not:
NoMethodError: undefined method `body' for ["Downstream app"]:Array
/Users/andrykonchin/projects/rack-contrib/test/spec_rack_simple_endpoint.rb:21:in `block (2 levels) in <top (required)>'
```
The tests fail because of recent changes in Rack. In Rack 2.0.1 body is always `Rack::BodyProxy` but in the latest versions body could be not buffered and returned as Array. 
Also Minitest deprecated global usage of `must_equal` and other matchers so instead of `a.must_equal 1` following DSL should be used `_(a).must_equal 1`. Example of warning:
``` …
```
> Fix tests warnings and failures

- lib/rack/contrib/locale.rb
- test/spec_rack_locale.rb
Fix some edge cases with handling `Accept-Language` header in the Locale middleware.
Changes:
- process correctly whitespaces
- ignore languages with `q=0`
- process correctly `Q=` prefix
- case insensitive matching
Closes https://github.com/rack/rack-contrib/issues/163
> Fix Locale middleware

- README.md
- lib/rack/contrib.rb
- lib/rack/contrib/json_body_parser.rb
- lib/rack/contrib/post_body_content_type_parser.rb
- test/spec_rack_json_body_parser_spec.rb
- test/spec_rack_post_body_content_type_parser.rb
This is a non-breaking (I hope!) refactor of PostBodyContentTypeParser, aimed at improving performance. It uses a couple of tactics to make things faster:
1. Skip parsing GET, OPTIONS and other bodiless HTTP requests by default. Because the HTTP spec disallows these request types from having a body, this change shouldn't affect anyone's app — although it is the change I'm most worried about. Seems worth the risk, though, because it improves performance of GET requests by 10x.
2. For POST, PATCH, and PUT requests, (a) read the content-type from `env` directly, instead of instantiating a `Rack::Request`, and (b) use Ruby 2.4's `String#match?` operator when available. These changes speed up the requests that do get parsed by 1.5x.
This PR also makes the middleware more liberal about what …
> Make PostBodyContentTypeParser 1.5x - 10x faster

- lib/rack/contrib/post_body_content_type_parser.rb
It's a common practice to accept block arguments in Rack middlewares.
So I just added examples of using the PostBodyContentTypeParser middleware
- w/o parameter
- w/ block parameter
- w/ converting `proc` to block parameter
Closes https://github.com/rack/rack-contrib/issues/162
> Documentation: add usage examples for PostBodyContentTypeParser

- test/spec_rack_access.rb
- test/spec_rack_backstage.rb
- test/spec_rack_bounce_favicon.rb
- test/spec_rack_callbacks.rb
- test/spec_rack_common_cookies.rb
- test/spec_rack_cookies.rb
- test/spec_rack_csshttprequest.rb
- test/spec_rack_deflect.rb
- test/spec_rack_enforce_valid_encoding.rb
- test/spec_rack_evil.rb
- test/spec_rack_expectation_cascade.rb
- test/spec_rack_garbagecollector.rb
- test/spec_rack_json_body_parser_spec.rb
- test/spec_rack_jsonp.rb
- test/spec_rack_lazy_conditional_get.rb
- test/spec_rack_lighttpd_script_name_fix.rb
- test/spec_rack_locale.rb
- test/spec_rack_mailexceptions.rb
- test/spec_rack_nested_params.rb
- test/spec_rack_post_body_content_type_parser.rb
- test/spec_rack_proctitle.rb
- test/spec_rack_profiler.rb
- test/spec_rack_relative_redirect.rb
- test/spec_rack_response_cache.rb
- test/spec_rack_response_headers.rb
- test/spec_rack_simple_endpoint.rb
- test/spec_rack_static_cache.rb
- test/spec_rack_try_static.rb
Changes:
- use `Rack::Lint` where it's missing
- fixed MiniTest deprecation warnings in the added recently `JSONBodyParser` middleware
- use `Timecop` where it's appropriate
> Improve tests

- lib/rack/contrib/runtime.rb
- test/spec_rack_runtime.rb
- created `rack/contrib/runtime.rb` file
- added minimalistic specs
Related PR:
- https://github.com/rack/rack-contrib/pull/170
`Rack::Runtime` was removed recently [here](https://github.com/rack/rack-contrib/pull/170) but because there is already compatible version in `rack` itself. But in order to support backward compatibility and allow to require this middleware directly, e.g.
```ruby
require 'rack/contrib/runtime'
```
we have to keep the file.
> Repair `lib/rack/contrib/runtime` file to make Rack::Runtime available

- lib/rack/contrib/csshttprequest.rb
- test/spec_rack_csshttprequest.rb
Return enumerable (Array) body in `CSSHTTPRequest` instead of string.
As far as nobody complained about this issue for many years looks like nobody uses it and it can be dropped from the gem.
It makes sense to revise all the middleware and keep only actual and which are in use now.
> Fix CSSHTTPRequest - body conforms to Rack SPEC

- lib/rack/contrib/access.rb
- lib/rack/contrib/common_cookies.rb
- lib/rack/contrib/deflect.rb
- lib/rack/contrib/lazy_conditional_get.rb
- test/spec_rack_deflect.rb
Some middleware use instance variables and it makes it not thread-safe.
Changes:
- fixed Rack::Access
- fixed Rack::CommonCookies
- fixed Rack::Deflect
- added warning for Rack::LazyConditionalGet
> Fix some thread-safety issues

- README.md
- lib/rack/contrib/config.rb
`Rack::Config` was imported to the `rack` gem in 2009 year (https://github.com/rack/rack/commit/a1534a5d7b48812e1e67d7ff02ef53b70e3ea492) so it doesn't make sense to keep the copy here in `rack-contrib`.
https://github.com/rack/rack/blob/2-2-stable/lib/rack/config.rb
Changes:
- removed Rack::Config
- keep the file and require a middleware from the `rack` gem
- updated Readme - removed the Rack::Config from the middleware list
> Remove Rack::Config middleware

- lib/rack/contrib/expectation_cascade.rb
- test/spec_rack_expectation_cascade.rb
`Rack::ExpectationCascade` worked incorrectly and used `env['Expect']` request header.  As far as all the request headers have `HTTP_` prefix the middleware should use `env['HTTP_EXPECT']` instead.
Changes:
- repair Rack::ExpectationCascade and use correct header name
As far as nobody complained about this issue for many years looks like nobody uses it and it can be dropped from the gem.
> Fix Rack::ExpectationCascade handling request headers

- lib/rack/contrib/common_cookies.rb
- lib/rack/contrib/csshttprequest.rb
- lib/rack/contrib/lazy_conditional_get.rb
- lib/rack/contrib/locale.rb
- lib/rack/contrib/relative_redirect.rb
- lib/rack/contrib/response_cache.rb
- lib/rack/contrib/static_cache.rb
- test/spec_rack_response_cache.rb
As far as HTTP headers names are case-insensitive a middleware cannot rely on conventional format of a header name. An application can return unexpected but still valid header name e.g. `CONTENT-TYPE` instead of conventional `Content-Type`.
There is a `Rack::Utils::HeaderHash` class in the `rack` gem which wraps headers and makes it case-insensitive. So there all the middleware which get or set response headers are updated in order to use `Rack::Utils::HeaderHash`.
Changes:
- updated Rack::CommonCookies
- updated Rack::CSSHTTPHeaders
- updated Rack::LazyConditionGet
- updated Rack::Locale
- updated Rack::RelativeRedirect
- updated Rack::ResponseCache
- updated Rack::StaticCache
> Fix issue with response headers case-insensitivity

- lib/rack/contrib/backstage.rb
- lib/rack/contrib/jsonp.rb
- lib/rack/contrib/mailexceptions.rb
- lib/rack/contrib/nested_params.rb
- lib/rack/contrib/signals.rb
Minor refactoring and fixes
Changes:
- Rack::Backstage - minor refactoring
- Rack::JSONP - minor refactoring
- Rack::MailExcpetion, Rack::NestedParams - removed excessive condition
- Rack::Signals - fixed issue with closing original response body
Unfortunately there is no any test for `Rack::Signals` so I didn't add any. Let me know if test for the fix is still required.
> Minor fixes

- lib/rack/contrib/json_body_parser.rb
- test/spec_rack_json_body_parser_spec.rb
Do not rescue JSON:ParserError if it was raised inside de app.
I was trying to figure out why my app was returning 400 until I found that it was due to a `JSON::ParserError` rescued by this middleware.
This PR makes the `rescue` block to only catch this exception if it was raised when parsing the params and not when it was raised by the app.
> Rack::JSONBodyParser. Do not rescue JSON:ParserError

- test/spec_rack_json_body_parser_spec.rb
Triggered by
TESTOPTS=--seed=8264 b e rake
Seen in CI: https://github.com/rack/rack-contrib/actions/runs/6319320196/job/17160038534#step:4:88
I don't think we should be checking this.
See https://github.com/rack/rack-contrib/commit/161eb9d190848254c331810e06feeaad25ec16aa
> Remove another crazy `JSONBodyParser` spec

- lib/rack/contrib/locale.rb
- test/spec_rack_locale.rb
We've noticed a few clients sending along funny locales like `English`
These result in the following error:
```
I18n::InvalidLocale: "En" is not a valid locale
```
That's happening because the locale variant match is case insensitive:
https://github.com/rack/rack-contrib/blob/main/lib/rack/contrib/locale.rb#L91
But then the locale is extracted without a downcase.
I believe it should be safe to just downcase the locale from the client in these cases.
> Treat locales with variants case insensitively
